name: Test Pipeline with Approval

on:
  workflow_dispatch:
    inputs:
      approval:
        description: 'Do you approve this deployment?'
        required: true
        default: 'false'  # Default to false to avoid accidental deployments

jobs:
  test_pipeline:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Just a message to indicate the start
    - name: Start Test Pipeline
      run: echo "Test pipeline started. Waiting for approval..."

    # Step 2: Pre-Approval before proceeding
    - name: Wait for Approval
      run: echo "Waiting for approval to proceed..."
      if: ${{ github.event.inputs.approval == 'true' }}

    # Step 3: Completion message
    - name: Pipeline Complete
      if: ${{ github.event.inputs.approval == 'true' }}
      run: echo "Approval received. Test pipeline completed successfully!"

    - name: Pipeline Complete
      if: ${{ github.event.inputs.approval == 'false' }}  # Only completes if approved
      run: echo "Approval received. Test pipeline not aprooved!"
