name: Test Pipeline with Approval

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test_pipeline:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Just a message to indicate the start
    - name: Start Test Pipeline
      run: echo "Test pipeline started. Waiting for approval..."

    # Step 2: Pre-Approval before proceeding
    - name: Wait for Approval
      run: echo "Waiting for approval to proceed..."
      if: ${{ github.event.inputs.approval == 'true' }}  # This waits for approval

    # Step 3: Completion message
    - name: Pipeline Complete
      if: ${{ github.event.inputs.approval == 'true' }}  # Only completes if approved
      run: echo "Approval received. Test pipeline completed successfully!"

    - name: Pipeline Complete
      if: ${{ github.event.inputs.approval == 'false' }}  # Only completes if approved
      run: echo "Approval received. Test pipeline not aprooved!"
